#
#IF TRANSPARENT = true THEN THE MESSAGES BELOW WILL NOT BE SHOWN TO THE PLAYER.
#I HAVE REMOVED MOST OF THE CONSOLE SPAM BUT I HOPE TO ADD A CLEAN WAY TO SEE IT
#IN THE FUTURE.
quote: The measure of a man is what he does with power.
name: Plato
adminmessage: Unfortunately We have seen your heart...
transparent: false
disableAnvils: true
disableEnchanting: false
canUseBannedEnchants: true
ARROW_DAMAGE: 2
ARROW_FIRE: 2
ARROW_INFINITE: 2
ARROW_KNOCKBACK: 2
DAMAGE_ALL: 2
DAMAGE_ARTHROPODS: 2
DAMAGE_UNDEAD: 2
DIG_SPEED: 2
DURABILITY: 2
FIRE_ASPECT: 2
KNOCKBACK: 2
LOOT_BONUS_BLOCKS: 2
LOOT_BONUS_MOBS: 2
OXYGEN: 2
PROTECTION_ENVIRONMENTAL: 2
PROTECTION_EXPLOSIONS: 2
PROTECTION_FALL: 2
PROTECTION_FIRE: 2
PROTECTION_PROJECTILE: 2
SILK_TOUCH: 2
WATER_WORKER: 2
THORNS: 2